// SPDX-FileCopyrightText: 2026 CERN
// SPDX-License-Identifier: LGPL-3.0-or-later

#ifndef ADAPTYST_INJECT_ERRORS_H_
#define ADAPTYST_INJECT_ERRORS_H_

#define ADAPTYST_INJECT_OK 0
#define ADAPTYST_INJECT_ERR_MISSING_RUNTIME_INFO 1
#define ADAPTYST_INJECT_ERR_INVALID_RUNTIME_INFO 2
#define ADAPTYST_INJECT_EXCEPTION 3
#define ADAPTYST_INJECT_ERR_INVALID_REPLY 4
#define ADAPTYST_INJECT_ERR_NOT_INITIALISED 5
#define ADAPTYST_INJECT_WARN_NOT_ALL_MODULES_SUCCEEDED 6
#define ADAPTYST_INJECT_ERR_TIMEOUT 7
#define ADAPTYST_INJECT_ERR_REGION_NOT_FOUND 8
#define ADAPTYST_INJECT_ERR_REGION_ALREADY_STARTED 9
#define ADAPTYST_INJECT_ERR_INVALID_REGION_STATE 10
#define ADAPTYST_INJECT_ERR_REGION_IN_DIFFERENT_UNIT 11

#endif
