name: linux

on: [push, pull_request]

jobs:

  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - uses: aidasoft/run-lcg-view@v3
      with:
        container: "el9"
        view-path: ""
        run: |
          source /cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Fri/Boost/1.87.0/x86_64-el9-gcc13-opt/Boost-env.sh
          source /cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Fri/libarchive/3.7.9/x86_64-el9-gcc13-opt/libarchive-env.sh
          mkdir build
          cd build
          echo "::group::CMakeConfig"
          cmake .. -G Ninja
          echo "::group::Compile"
          ninja
